# -*- coding: utf-8 -*-
"""seaborn.scatterplot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OPMa-U0cYXrgGGnBE3q7WDD97UiDAuex

Kerakli kutibxonalarni chaqirib olamiz:
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

"""Ma'lumotlarni yuklab olamiz"""

tips = sns.load_dataset("tips")
tips.head()

"""`scatterplot` orqali grafik chizamiz"""

sns.scatterplot(data=tips, x="total_bill", y="tip")
plt.show()

"""`hue` orqali turli ranglar bilan ajratamiz"""

sns.scatterplot(data=tips, x="total_bill", y="tip", hue="time")
plt.show()

"""Bir xil o‘zgaruvchini style parametriga belgilash ham markerlarni (belgilarni) o‘zgartiradi va yanada qulayroq, tushunarliroq grafik yaratadi."""

sns.scatterplot(data=tips, x="total_bill", y="tip", hue="time", style="time")
plt.show()

"""Turli xil o'zgaruvchilarga rang va uslubni belgilash ranglar va markerlarni mustaqil ravishda o'zgartiradi:"""

sns.scatterplot(data=tips, x="total_bill", y="tip", hue="day", style="time")
plt.show()

"""Agar rangga tayinlangan o'zgaruvchi raqamli bo'lsa, semantik xaritalash miqdoriy bo'ladi va boshqa standart palitradan foydalanadi:"""

sns.scatterplot(data=tips, x="total_bill", y="tip", hue="size")
plt.show()

"""`hue` o‘zgaruvchisiga kategoriya bo‘yicha rang berishni majburiy qilish uchun, kategoriya palitrasi nomini yoki aniq ranglarni (Python ro‘yxati yoki lug‘ati ko‘rinishida) uzating."""

sns.scatterplot(data=tips, x="total_bill", y="tip", hue="size", palette="deep")
plt.show()

tip_rate = tips.eval("tip / total_bill").rename("tip_rate")
sns.scatterplot(data=tips, x="total_bill", y="tip", hue=tip_rate)
plt.show()

"""Sonli o‘zgaruvchini nuqtalar maydoniga semantik bog‘lanishni qo‘llash uchun o‘lchamga (`size`) biriktirish mumkin."""

sns.scatterplot(data=tips, x="total_bill", y="tip", hue="size", size="size")
plt.show()

sns.scatterplot(
    data=tips, x="total_bill", y="tip", hue="size", size="size",
    sizes=(20, 200), legend="full"
)
plt.show()

"""`relplot()` funksiyasidan foydalanib `scatterplot()` va FacetGrid ni birlashtiring.
Bu qo‘shimcha kategorik o‘zgaruvchilar bo‘yicha guruhlash va ularni bir nechta kichik grafiklarda (subplotlarda) chizishga imkon beradi.

`relplot()` dan foydalanish FacetGrid ni bevosita ishlatishga qaraganda xavfsizroq, chunki u barcha fasetlar (kichik grafiklar) bo‘ylab semantik mosliklarni (rang, o‘lcham, uslub kabi) bir xil tarzda sinxronlashtirib beradi.
"""

sns.relplot(
    data=tips, x="total_bill", y="tip",
    col="time", hue="day", style="day",
    kind="scatter"
)
plt.show()