# -*- coding: utf-8 -*-
"""seaborn.scatterplot-ma'lumot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OPMa-U0cYXrgGGnBE3q7WDD97UiDAuex

#seaborn.scatterplot()
#seaborn.scatterplot(data=None, *, x=None, y=None, hue=None, size=None, style=None, palette=None, hue_order=None, hue_norm=None, sizes=None, size_order=None, size_norm=None, markers=True, style_order=None, legend='auto', ax=None, **kwargs)

#Bir nechta semantik guruhlash imkoniyati bilan `scatter` (nuqta) grafik chizing.

#X va Y o‘rtasidagi munosabatni ma’lumotlarning turli kichik to‘plamlari `(subsets)` uchun `hue`, `size` va `style` parametrlaridan foydalanib ko‘rsatish mumkin.
#Bu parametrlar turli kichik to‘plamlarni ajratib ko‘rsatishda ishlatiladigan vizual semantika turlarini boshqaradi.
#Uchala semantik turdan bir vaqtning o‘zida foydalanib, mustaqil ravishda uch o‘lchovni ko‘rsatish mumkin, ammo bunday uslubdagi grafikni talqin qilish qiyin bo‘lishi mumkin va ko‘pincha samarasiz bo‘ladi.
#Bir xil o‘zgaruvchi uchun hue va styleni birga ishlatish (ya’ni ortiqcha semantika) grafikani yanada tushunarliroq qilishda yordam beradi.

#Agar `hue` (va qisman `size`) semantikasi mavjud bo‘lsa, ularning standart ishlov berilishi o‘zgaruvchining “sonli” yoki “kategorik” ekanligi aniqlanishiga bog‘liq bo‘ladi.
#Xususan, sonli o‘zgaruvchilar odatda ketma-ket rang xaritasi (sequential colormap) bilan ifodalanadi va legenda yozuvlari ma’lumotlarda mavjud bo‘lishi yoki bo‘lmasligi mumkin bo‘lgan muntazam “tick” qiymatlarini ko‘rsatadi.
#Bu xatti-harakatni turli parametrlar orqali boshqarish mumkin, buni quyida tavsif va misollar orqali ko‘rish mumkin.

#`lineplot`
#Ma’lumotlarni chiziqlar yordamida chizib ko‘rsatadi.

#`stripplot`
#Kategoriyaga asoslangan nuqtali (scatter) diagramma chizadi va nuqtalarni biroz siljitib (jitter) joylashtiradi.

#`swarmplot`
#Kategoriyaga asoslangan nuqtali (scatter) diagramma chizadi va nuqtalarni bir-biriga to‘g‘ri kelmasligi uchun tartibli holda joylashtiradi.
"""