# -*- coding: utf-8 -*-
"""seaborn.heatmap

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gtfDWqiDXP-bDApyZUesMwxrp0624EhZ

#seaborn.heatmap()
###`seaborn.heatmap`(data, *, vmin=None, vmax=None, cmap=None, center=None, robust=False, annot=None, fmt='.2g', annot_kws=None, linewidths=0, linecolor='white', cbar=True, cbar_kws=None, cbar_ax=None, square=False, xticklabels='auto', yticklabels='auto', mask=None, ax=None, **kwargs)

##Bu `Axes-level` function hisoblanadi va agar `ax` argumentiga hech narsa berilmasa, joriy faol `Axes` ichiga `heatmap` (issiqlik xaritasi) ni chizadi.

##Ushbu `Axes` joyining bir qismi `colormap` (ranglar xaritasi) ni chizish uchun ishlatiladi, agar `cbar=False` qilinmasa yoki alohida `Axes` `cbar_ax` orqali taqdim etilmasa.
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

glue = sns.load_dataset("glue").pivot(index="Model", columns="Task", values="Score")
sns.heatmap(glue)
plt.show()

sns.heatmap(glue, annot=True)
plt.show()

sns.heatmap(glue, annot=True, fmt=".1f")
plt.show()

sns.heatmap(glue, annot=glue.rank(axis="columns"))
plt.show()

sns.heatmap(glue, annot=True, linewidth=.5)
plt.show()

sns.heatmap(glue, cmap="crest")
plt.show()

sns.heatmap(glue, cmap=sns.cubehelix_palette(as_cmap=True))
plt.show()

sns.heatmap(glue, vmin=50, vmax=100)
plt.show()

ax = sns.heatmap(glue, annot=True)
ax.set(xlabel="", ylabel="")
ax.xaxis.tick_top()
plt.show()

