# -*- coding: utf-8 -*-
"""seaborn.barplot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12DQ6TnI9VWMEsSJEEIiEMNrG1c92gLSE

#seaborn.barplot
`seaborn.barplot`(data=None, *, x=None, y=None, hue=None, order=None, hue_order=None, estimator='mean', errorbar=('ci', 95), n_boot=1000, seed=None, units=None, weights=None, orient=None, color=None, palette=None, saturation=0.75, fill=True, hue_norm=None, width=0.8, dodge='auto', gap=0, log_scale=None, native_scale=False, formatter=None, legend='auto', capsize=0, err_kws=None, ci=<deprecated>, errcolor=<deprecated>, errwidth=<deprecated>, ax=None, **kwargs)

##Chiziqli chiziq har bir to'rtburchakning balandligi bilan raqamli o'zgaruvchi uchun yig'indisi yoki statistik bahosini ifodalaydi va xato satridan foydalanib, ushbu taxmin atrofidagi noaniqlikni ko'rsatadi. Shtrixli chizmalar o'q oralig'ida 0 ni o'z ichiga oladi va 0 o'zgaruvchi uchun ma'noli qiymat bo'lsa, ular yaxshi tanlovdir.
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

penguins = sns.load_dataset("penguins")
sns.barplot(penguins, x="island", y="body_mass_g")
plt.show()

sns.barplot(penguins, x="body_mass_g", y="island", hue="island", legend=False)
plt.show()

flights = sns.load_dataset("flights")
flights_wide = flights.pivot(index="year", columns="month", values="passengers")
sns.barplot(flights_wide)
plt.show()

sns.barplot(flights_wide["Jun"])
plt.show()

sns.barplot(penguins, x="island", y="body_mass_g", hue="sex")
plt.show()

sns.barplot(penguins, x="island", y="body_mass_g", errorbar="sd")
plt.show()

ax = sns.barplot(flights, x="year", y="passengers", estimator="sum", errorbar=None)
ax.bar_label(ax.containers[0], fontsize=10)
plt.show()

ax = sns.barplot(
    flights, x="year", y="passengers",
    native_scale=True,
    estimator="sum", errorbar=None,
)
ax.plot(1957, 4500, "*", markersize=10, color="r")
plt.show()