# -*- coding: utf-8 -*-
"""seaborn.regplot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dYeruqjIjF0Q2bY1YZNeBrg54DMQZC7R

#seaborn.regplot
###`seaborn.regplot`(data=None, *, x=None, y=None, x_estimator=None, x_bins=None, x_ci='ci', scatter=True, fit_reg=True, ci=95, n_boot=1000, units=None, seed=None, order=1, logistic=False, lowess=False, robust=False, logx=False, x_partial=None, y_partial=None, truncate=True, dropna=True, x_jitter=None, y_jitter=None, label=None, color=None, marker='o', scatter_kws=None, line_kws=None, ax=None)

##Regressiya modelini baholash uchun bir-birini istisno qiluvchi (bir vaqtning o‘zida ishlatilmaydigan) bir nechta variantlar mavjud. Batafsil ma’lumot uchun qo‘llanmaga (tutorial) qarang.

#Eslatma

`regplot()` va `lmplot()` funksiyalari bir-biri bilan chambarchas bog‘liq, lekin `regplot()` — bu axes-level function (ya’ni bitta koordinata o‘qi doirasida ishlaydi), `lmplot()` esa — figure-level function bo‘lib, u
`regplot()` va `FacetGrid`ni birlashtiradi.

Shuningdek, `regplot()`ni `JointGrid` yoki `PairGrid` bilan birlashtirish ham oson. Buni `jointplot()` va `pairplot()` funksiyalari orqali qilish mumkin, ammo ular `regplot()`ning barcha parametrlari bilan to‘liq ishlay olmaydi.
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
# %matplotlib inline

mpg = sns.load_dataset('mpg')
sns.regplot(data=mpg, x="weight", y="acceleration")
plt.show()

sns.regplot(data=mpg, x="weight", y="mpg", order=2)
plt.show()

sns.regplot(data=mpg, x="displacement", y="mpg", logx=True)
plt.show()

sns.regplot(data=mpg, x="horsepower", y="mpg", lowess=True)
plt.show()

sns.regplot(x=mpg["weight"], y=mpg["origin"].eq("usa").rename("from_usa"), logistic=True)
plt.show()

sns.regplot(data=mpg, x="horsepower", y="weight", robust=True)
plt.show()

sns.regplot(data=mpg, x="weight", y="horsepower", ci=None)
plt.show()

sns.regplot(data=mpg, x="cylinders", y="weight", x_jitter=.15)
plt.show()

sns.regplot(data=mpg, x="cylinders", y="acceleration", x_estimator=np.mean, order=2)
plt.show()

sns.regplot(data=mpg, x="weight", y="mpg", x_bins=np.arange(2000, 5500, 250), order=2)
plt.show()

