# -*- coding: utf-8 -*-
"""seaborn.pointplot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TdhdMZyB5k5zBPgGl6MXbT9Sfn6oWO9i

#seaborn.pointplot()
`seaborn.pointplot`(data=None, *, x=None, y=None, hue=None, order=None, hue_order=None, estimator='mean', errorbar=('ci', 95), n_boot=1000, seed=None, units=None, weights=None, color=None, palette=None, hue_norm=None, markers=<default>, linestyles=<default>, dodge=False, log_scale=None, native_scale=False, orient=None, capsize=0, formatter=None, legend='auto', err_kws=None, ci=<deprecated>, errwidth=<deprecated>, join=<deprecated>, scale=<deprecated>, ax=None, **kwargs)

##Nuqta grafigi nuqta o'rni bo'yicha raqamli o'zgaruvchining markaziy tendentsiyasini baholashni ifodalaydi va xato satrlari yordamida ushbu taxmin atrofida noaniqlikning ba'zi ko'rsatkichlarini beradi.

##Bir yoki bir nechta toifali o'zgaruvchilarning turli darajalari o'rtasidagi taqqoslashlarni yo'naltirish uchun nuqtali chizmalar chiziqli chizmalardan ko'ra foydaliroq bo'lishi mumkin. Ular, ayniqsa, o'zaro ta'sirlarni ko'rsatishda mohir: bitta toifali o'zgaruvchining darajalari o'rtasidagi munosabatlar ikkinchi toifali o'zgaruvchining darajalari bo'yicha qanday o'zgarishi. Har bir nuqtani bir xil rang darajasidan birlashtiradigan chiziqlar o'zaro ta'sirlarni nishabdagi farqlar bilan baholashga imkon beradi, bu ko'zlar uchun bir nechta nuqta yoki novdalar guruhining balandliklarini solishtirishdan ko'ra osonroqdir.
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

penguins = sns.load_dataset('penguins')
sns.pointplot(data=penguins, x="island", y="body_mass_g")
plt.show()

sns.pointplot(data=penguins, x="island", y="body_mass_g", hue="sex")
plt.show()

sns.pointplot(
    data=penguins,
    x="island", y="body_mass_g", hue="sex",
    markers=["o", "s"], linestyles=["-", "--"],
)
plt.show()

sns.pointplot(data=penguins, x="island", y="body_mass_g", errorbar="sd")
plt.show()

sns.pointplot(data=penguins, x="sex", y="bill_depth_mm", hue="species", dodge=True)
plt.show()

flights = sns.load_dataset('flights')
flights_wide = flights.pivot(index="year", columns="month", values="passengers")
sns.pointplot(flights_wide)
plt.show()

sns.pointplot(flights_wide["Jun"])
plt.show()

sns.pointplot(flights_wide["Jun"], formatter=lambda x: f"'{x % 1900}")
plt.show()

ax = sns.pointplot(flights_wide["Jun"], native_scale=True)
ax.plot(1957, 440, marker="*", color="r", markersize=10)
plt.show()