# -*- coding: utf-8 -*-
"""seaborn.swarmplot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1875wdCe_XtiYN86kKpE9D8Z_OV5nUAPM

#seaborn.swarmplot
`seaborn.swarmplot`(data=None, *, x=None, y=None, hue=None, order=None, hue_order=None, dodge=False, orient=None, color=None, palette=None, size=5, edgecolor=None, linewidth=0, hue_norm=None, log_scale=None, native_scale=False, formatter=None, legend='auto', warn_thresh=0.05, ax=None, **kwargs)

`Kategorik scatterplot` (sochilma diagramma) ni chiziqlar ustida nuqtalar bir-birini yopib qolmasligi uchun moslashtirilgan holda chizish mumkin.

Bu funksiya `stripplot()` ga o‘xshaydi, faqat nuqtalar (faqat kategorik o‘q bo‘yicha) bir-birini to‘smasligi uchun siljitib joylashtiriladi. Bu usul qiymatlarning taqsimotini yanada aniqroq ko‘rsatadi, lekin juda katta miqdordagi kuzatuvlar uchun samarali emas. Ushbu turdagi diagramma ba’zan `“beeswarm”` (ari uyi) deb ataladi.

`Swarm plot` mustaqil ham chizilishi mumkin, lekin `box plot` yoki `violin plot` ga yaxshi qo‘shimcha bo‘ladi. Ayniqsa, barcha kuzatuvlarni ko‘rsatish bilan birga taqsimotning umumiy shaklini ham namoyish qilishni xohlaganda foydali.
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

"""Avvalvi datadan foydalanamiz:"""

tips = sns.load_dataset("tips")
sns.swarmplot(data=tips, x="total_bill")
plt.show()

sns.swarmplot(data=tips, x="total_bill", y="day")
plt.show()

sns.swarmplot(data=tips, x="day", y="total_bill")
plt.show()

sns.swarmplot(data=tips, x="total_bill", y="day", hue="day", legend=False)
plt.show()

sns.swarmplot(data=tips, x="total_bill", y="day", hue="sex")
plt.show()

"""#stripplotda kabi foydalansak bo'ladi natijalar o'xshash chiqadi"""

sns.swarmplot(
    data=tips, x="total_bill", y="day",
    marker="x", linewidth=1,
)
plt.show()

