# -*- coding: utf-8 -*-
"""seaborn.rugplot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P00A_PWN2H5U0uSOEWbEtIMD3XOrdwlg

##seaborn.rugplot
`seaborn.rugplot`(data=None, *, x=None, y=None, hue=None, height=0.025, expand_margins=True, palette=None, hue_order=None, hue_norm=None, legend=True, ax=None, **kwargs)

Chekka taqsimotlarni x va y o‘qlari bo‘ylab chiziqchalar (`ticks`) chizish orqali tasvirlang.

Bu funksiya boshqa grafiklarni to‘ldirish uchun mo‘ljallangan bo‘lib, u alohida kuzatuvlarning joylashuvini sezilarsiz tarzda ko‘rsatadi.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.pyplot as plt

import seaborn as sns; sns.set_theme()
tips = sns.load_dataset("tips")
sns.kdeplot(data=tips, x="total_bill")
sns.rugplot(data=tips, x="total_bill")
plt.show()

sns.scatterplot(data=tips, x="total_bill", y="tip")
sns.rugplot(data=tips, x="total_bill", y="tip")
plt.show()

sns.scatterplot(data=tips, x="total_bill", y="tip", hue="time")
sns.rugplot(data=tips, x="total_bill", y="tip", hue="time")
plt.show()

sns.scatterplot(data=tips, x="total_bill", y="tip")
sns.rugplot(data=tips, x="total_bill", y="tip", height=.1)
plt.show()

sns.scatterplot(data=tips, x="total_bill", y="tip")
sns.rugplot(data=tips, x="total_bill", y="tip", height=-.02, clip_on=False)
plt.show()

diamonds = sns.load_dataset("diamonds")
sns.scatterplot(data=diamonds, x="carat", y="price", s=5)
sns.rugplot(data=diamonds, x="carat", y="price", lw=1, alpha=.005)
plt.show()

