# -*- coding: utf-8 -*-
"""seaborn.boxplot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L7V9_TpBdKUa-rnffeo5VazdNXh7Mo37

#seaborn.boxplot
`seaborn.boxplot`(data=None, *, x=None, y=None, hue=None, order=None, hue_order=None, orient=None, color=None, palette=None, saturation=0.75, fill=True, dodge='auto', width=0.8, gap=0, whis=1.5, linecolor='auto', linewidth=None, fliersize=None, hue_norm=None, native_scale=False, log_scale=None, formatter=None, legend='auto', ax=None, **kwargs)

Qutb (`box`) diagrammasini kategoriyalar bo‘yicha taqsimotlarni ko‘rsatish uchun chizamiz.

`Box plot` (yoki `box-and-whisker plot`) kvantitativ ma’lumotlarning taqsimotini shunday ko‘rsatadiki, o‘zgaruvchilar orasidagi yoki kategorik o‘zgaruvchining darajalari bo‘yicha solishtirishni osonlashtiradi. Quti (`box`) ma’lumotlar to‘plamining kvartillarini ko‘rsatadi, `whisker’`lar esa taqsimotning qolgan qismini cho‘zib beradi — faqatgina interkvartil oralig‘iga (`IQR`) asoslangan usul bilan `«outlier»` deb topilgan nuqtalar whisker tashqarisida qoladi.
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

df = sns.load_dataset("titanic")
df.head()

sns.boxplot(x=df["age"])
plt.show()

sns.boxplot(data=df, x="age", y="class")
plt.show()

sns.boxplot(data=df, x="class", y="age", hue="alive")
plt.show()

sns.boxplot(data=df, x="class", y="age", hue="alive", fill=False, gap=.1)
plt.show()

sns.boxplot(data=df, x="age", y="deck", whis=(0, 100))
plt.show()

sns.boxplot(data=df, x="age", y="deck", width=.5)
plt.show()

sns.boxplot(data=df, x="age", y="deck", color=".8", linecolor="#137", linewidth=.75)
plt.show()