# -*- coding: utf-8 -*-
"""seaborn.stripplot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1feZycwmgT8iHhF7EISVfDfBJJ7H9VzrL

#seaborn.stripplot
`seaborn.stripplot`(data=None, *, x=None, y=None, hue=None, order=None, hue_order=None, jitter=True, dodge=False, orient=None, color=None, palette=None, size=5, edgecolor=<default>, linewidth=0, hue_norm=None, log_scale=None, native_scale=False, formatter=None, legend='auto', ax=None, **kwargs)

`Strip plot` (chiziqcha nuqta diagrammasi) o‘zicha chizilishi mumkin, lekin u `box plot` (quti diagramma) yoki `violin plot` (skripka diagramma) ga yaxshi qo‘shimcha ham bo‘ladi. Ayniqsa, barcha kuzatuvlarni ko‘rsatish bilan birga ma’lumotlarning taqsimoti haqida umumiy tasavvur berishni xohlaganda foydali bo‘ladi.

Kerakli kutibxonalarni chaqirib olamiz:
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

tips = sns.load_dataset("tips")
tips.head()

sns.stripplot(data=tips, x="total_bill")
plt.show()

sns.stripplot(data=tips, x="total_bill", y="day")
plt.show()

sns.stripplot(data=tips, x="day", y="total_bill")
plt.show()

sns.stripplot(data=tips, x="total_bill", y="day", hue="day", legend=False)
plt.show()

sns.stripplot(data=tips, x="total_bill", y="day", hue="sex")
plt.show()

sns.stripplot(data=tips, x="total_bill", y="day", hue="size")
plt.show()

sns.stripplot(data=tips, x="total_bill", y="day", hue="size", palette="deep")
plt.show()

sns.stripplot(data=tips, x="total_bill", y="day", hue="sex", dodge=True)
plt.show()

sns.stripplot(data=tips, x="total_bill", y="day", hue="sex", dodge=True, jitter=False)
plt.show()

sns.stripplot(data=tips)
plt.show()

sns.stripplot(data=tips, orient="h")
plt.show()

sns.stripplot(
    data=tips, x="total_bill", y="day", hue="time",
    jitter=False, s=20, marker="D", linewidth=1, alpha=.1,
)
plt.show()

sns.catplot(data=tips, x="time", y="total_bill", hue="sex", col="day", aspect=.5)
plt.show()

