# -*- coding: utf-8 -*-
"""seaborn.residplot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gtfDWqiDXP-bDApyZUesMwxrp0624EhZ

#seaborn.residplot()
###`seaborn.residplot`(data=None, *, x=None, y=None, x_partial=None, y_partial=None, lowess=False, order=1, robust=False, dropna=True, label=None, color=None, scatter_kws=None, line_kws=None, ax=None)

##Bu funksiya `y` ni `x` ga regressiya qiladi (ehtimol robust yoki polinomial regressiya sifatida) va keyin qoldiqlar (`residuals`) ning scatterplot (nuqtali grafik) chizadi.

##Ixtiyoriy ravishda `lowess` silliqlash (`smoothing`) usulini qoldiq grafigiga qo‘shishingiz mumkin, bu qoldiqlarda qandaydir tuzilma (`structure`) bor-yo‘qligini aniqlashda yordam beradi.
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

mpg = sns.load_dataset('mpg')
sns.residplot(data=mpg, x="weight", y="displacement")
plt.show()

sns.residplot(data=mpg, x="horsepower", y="mpg")
plt.show()

sns.residplot(data=mpg, x="horsepower", y="mpg", order=2)
plt.show()

sns.residplot(data=mpg, x="horsepower", y="mpg", lowess=True, line_kws=dict(color="r"))
plt.show()