# -*- coding: utf-8 -*-
"""seaborn.countplot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17Herhh0gsvy3pFUrrlx1lLAVtjcJ9Sqi

#seaborn.countplot()
###`seaborn.countplot`(data=None, *, x=None, y=None, hue=None, order=None, hue_order=None, orient=None, color=None, palette=None, saturation=0.75, fill=True, hue_norm=None, stat='count', width=0.8, dodge='auto', gap=0, log_scale=None, native_scale=False, formatter=None, legend='auto', ax=None, **kwargs)

##`countplot` (sonli diagramma) ni histogramma deb o‘ylash mumkin, faqat bu yerda u miqdoriy emas, balki kategoriyaviy o‘zgaruvchi bo‘yicha tuziladi. Uning asosiy API (qo‘llanish usuli) va parametr sozlamalari `barplot()` bilan bir xil, shuning uchun ichki (nested) o‘zgaruvchilar bo‘yicha sonlarni solishtirish mumkin.

##E’tibor bering, `histplot()` funksiyasi ham shunga o‘xshash imkoniyatlarni beradi, lekin unda qo‘shimcha xususiyatlar mavjud (masalan, ustunlarni bir-birining ustiga joylash — `bar stacking`). Shuningdek, `histplot()` ning standart (default) ishlash usuli `countplot()` dan biroz farq qiladi.
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

"""kerakli datani yuklab olamiz:"""

titanic = sns.load_dataset('titanic')
titanic.head()

sns.countplot(titanic, x="class")
plt.show()

sns.countplot(titanic, x="class", hue="survived")
plt.show()

sns.countplot(titanic, x="class", hue="survived", stat="percent")
plt.show()

