# -*- coding: utf-8 -*-
"""seaborn.Implot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EVeyKf5m9dr24GVhHljH13Ae60UGClEy

#seaborn.lmplot
###`seaborn.lmplot`(data, *, x=None, y=None, hue=None, col=None, row=None, palette=None, col_wrap=None, height=5, aspect=1, markers='o', sharex=None, sharey=None, hue_order=None, col_order=None, row_order=None, legend=True, legend_out=None, x_estimator=None, x_bins=None, x_ci='ci', scatter=True, fit_reg=True, ci=95, n_boot=1000, units=None, seed=None, order=1, logistic=False, lowess=False, robust=False, logx=False, x_partial=None, y_partial=None, truncate=True, x_jitter=None, y_jitter=None, scatter_kws=None, line_kws=None, facet_kws=None)

Bu funksiya `regplot()` va `FacetGrid`ni birlashtiradi. U ma’lumotlar
to‘plamining shartli kichik to‘plamlari (subsets) bo‘yicha regressiya modellarini moslashtirish uchun qulay interfeys sifatida mo‘ljallangan.

O‘zgaruvchilarni turli facetlarga (bo‘laklarga) taqsimlash haqida o‘ylaganda, umumiy qoida shunday: eng muhim taqqoslash uchun `hue` dan foydalanish maqsadga muvofiq, undan keyin `col` va `row` keladi. Lekin har doim o‘z ma’lumotlaringiz xususiyatini va chizayotgan vizualizatsiya maqsadini inobatga olish kerak.

Regressiya modelini baholash uchun bir-birini istisno qiluvchi (mutually exclusive) bir qancha variantlar mavjud. Batafsil ma’lumot uchun qo‘llanmani (tutorial) ko‘ring.

Bu funksiyaning parametrlari `FacetGrid` dagi deyarli barcha imkoniyatlarni o‘z ichiga oladi. Ammo ba’zi hollarda `FacetGrid` klassi va `regplot()` ni alohida ishlatishingizga to‘g‘ri kelishi mumkin.
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

penguins = sns.load_dataset("penguins")
sns.lmplot(data=penguins, x="bill_length_mm", y="bill_depth_mm")
plt.show()

sns.lmplot(data=penguins, x="bill_length_mm", y="bill_depth_mm", hue="species")
plt.show()

sns.lmplot(
    data=penguins, x="bill_length_mm", y="bill_depth_mm",
    hue="species", col="sex", height=4,
)
plt.show()

sns.lmplot(
    data=penguins, x="bill_length_mm", y="bill_depth_mm",
    col="species", row="sex", height=3,
)
plt.show()

