# -*- coding: utf-8 -*-
"""seaborn.boxenplot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tGxB5_SO-940hOg3SGMasMR5W2yN7YCO

#seaborn.boxenplot
`seaborn.boxenplot`(data=None, *, x=None, y=None, hue=None, order=None, hue_order=None, orient=None, color=None, palette=None, saturation=0.75, fill=True, dodge='auto', width=0.8, gap=0, linewidth=None, linecolor=None, width_method='exponential', k_depth='tukey', outlier_prop=0.007, trust_alpha=0.05, showfliers=True, hue_norm=None, log_scale=None, native_scale=False, formatter=None, legend='auto', scale=<deprecated>, box_kws=None, flier_kws=None, line_kws=None, ax=None, **kwargs)

Ushbu syujet uslubi dastlab "harf qiymati" syujeti deb nomlangan, chunki u "harf qiymatlari" sifatida belgilangan ko'p sonli kvantlarni ko'rsatadi. Bu taqsimotning parametrik bo'lmagan ko'rinishini tuzishda quti syujetiga o'xshaydi, unda barcha xususiyatlar haqiqiy kuzatuvlarga mos keladi. Ko'proq kvantillarni chizish orqali u tarqalish shakli haqida, xususan, quyruqlarda ko'proq ma'lumot beradi.
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

diamonds = sns.load_dataset("diamonds")
diamonds.head()

sns.boxenplot(x=diamonds["price"])
plt.show()

sns.boxenplot(data=diamonds, x="price", y="clarity")
plt.show()

sns.boxenplot(data=diamonds, x="price", y="clarity", width_method="linear")
plt.show()

sns.boxenplot(data=diamonds, x="price", y="clarity", width=.5)
plt.show()

sns.boxenplot(data=diamonds, x="price", y="clarity", hue="clarity",  fill=False)
plt.show()

