"""seaborn_relplot-ma'lumot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X0GF_v_8yBiH9dM9KwpOM8WXRk3iAinl

# ##seaborn.relplot
`seaborn.relplot`(data=None, *, x=None, y=None, hue=None, size=None, style=None, units=None, weights=None, row=None, col=None, col_wrap=None, row_order=None, col_order=None, palette=None, hue_order=None, hue_norm=None, sizes=None, size_order=None, size_norm=None, markers=None, dashes=None, style_order=None, legend='auto', kind='scatter', height=5, aspect=1, facet_kws=None, **kwargs)

FacetGrid ustida munosabatli (relational) grafiklar chizish uchun figure-darajadagi interfeys.

Bu funksiya ikki o‘zgaruvchi orasidagi bog‘liqlikni ko‘rsatadigan bir nechta axes-darajadagi funksiyalarga murojaat qilish imkonini beradi.
kind parametri esa qaysi asosiy funksiyadan foydalanishni tanlaydi:

`scatterplot()` — kind="scatter" bo‘lsa (standart holat)

`lineplot()` — kind="line" bo‘lsa


Qo‘shimcha kalit argumentlar tanlangan asosiy funksiyaga uzatiladi.
Shuning uchun har bir kind uchun maxsus sozlamalarni bilish uchun o‘sha funksiya hujjatiga murojaat qilish tavsiya etiladi.

x va y o‘zgaruvchilar orasidagi bog‘liqlikni ma’lumotlarning turli kichik to‘plamlari uchun `hue`, `size` va `style` parametrlari yordamida ko‘rsatish mumkin.
Bu parametrlarda qaysi vizual belgilar orqali kichik to‘plamlarni farqlash aniqlanadi.
Uchala semantik turdan birgalikda foydalangan holda mustaqil ravishda uchta o‘lchovgacha ko‘rsatish mumkin, lekin bunday turdagi grafikni tushunish qiyin bo‘lishi va ko‘pincha samarasiz bo‘lishi mumkin.
Bir xil o‘zgaruvchi uchun bir vaqtning o‘zida hue va styleni qo‘llash (ya’ni takroriy semantika) grafikani yanada qulay va hamma uchun tushunarli qilishga yordam beradi.

Agar `hue` (va biroz darajada `size`) ishlatilsa, ularning standart ishlov berilishi o‘zgaruvchining sonli yoki kategorik ekanligi bilan bog‘liq.
Xususan, sonli o‘zgaruvchilar odatda ketma-ket ranglar xaritasi (`sequential colormap`) bilan tasvirlanadi, va legenda (izoh)da ma’lumotda bo‘lishi yoki bo‘lmasligi mumkin bo‘lgan muntazam qiymat belgilari (`ticks`) ko‘rsatiladi.
Bu xatti-harakatni turli parametrlar orqali boshqarish mumkin, quyida shu haqida tavsif va misollar keltirilgan.

Grafik chizilgandan so‘ng, unga tegishli `FacetGrid` obyekti qaytariladi.
Bu obyektni bevosita grafikning qo‘shimcha elementlarini sozlash yoki boshqa qatlamlar qo‘shish uchun ishlatish mumkin.
"""

