# -*- coding: utf-8 -*-
"""seaborn.displot-kodlar

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZS9wD4H4YHNCx_aX_mSrMu9Z_3eViVvn

Kerakli kutubxonalarni chaqirib olamiz:
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

"""Kerakli ma'lumotlarni yuklab olamiz:"""

penguins = sns.load_dataset("penguins")
penguins.head()

"""displot orqali Ustunli diagramma tuzamiz:"""

sns.displot(data=penguins, x="flipper_length_mm")
plt.show()

"""Turlicha tasvirlash usulini tanlash uchun `kind` parametridan foydalaning."""

sns.displot(data=penguins, x="flipper_length_mm", kind="kde")
plt.show()

"""Uchta asosiy grafik turi mavjud; gistogrammalar va yadroviy zichlik baholari (KDE) dan tashqari, empirik kumulyativ taqsimot funksiyalarini (ECDF) ham chizish mumkin."""

sns.displot(data=penguins, x="flipper_length_mm", kind="ecdf")
plt.show()

sns.displot(data=penguins, x="flipper_length_mm", kde=True)
plt.show()

sns.displot(data=penguins, x="flipper_length_mm", y="bill_length_mm")
plt.show()

sns.displot(data=penguins, x="flipper_length_mm", y="bill_length_mm", kind="kde")
plt.show()

"""Har bir grafik turida, alohida kuzatuvlarni ham qo‘shimcha chekka (‘rug’) orqali ko‘rsatish mumkin."""

g = sns.displot(data=penguins, x="flipper_length_mm", y="bill_length_mm", kind="kde", rug=True)
plt.show()

sns.displot(data=penguins, x="flipper_length_mm", hue="species", kind="kde")
plt.show()

"""Qo‘shimcha kalit so‘z argumentlari mos keluvchi asosiy chizish funksiyasiga uzatiladi va bu yanada kengroq sozlash imkonini beradi."""

sns.displot(data=penguins, x="flipper_length_mm", hue="species", multiple="stack")
plt.show()

