# -*- coding: utf-8 -*-
"""seaborn.catplot-ma'lumotlar

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NXIwGWSu53iZHbye4ggBJa4DNQRv3Vs1

#seaborn.catplot
`seaborn.catplot`(data=None, *, x=None, y=None, hue=None, row=None, col=None, kind='strip', estimator='mean', errorbar=('ci', 95), n_boot=1000, seed=None, units=None, weights=None, order=None, hue_order=None, row_order=None, col_order=None, col_wrap=None, height=5, aspect=1, log_scale=None, native_scale=False, formatter=None, orient=None, color=None, palette=None, hue_norm=None, legend='auto', legend_out=True, sharex=True, sharey=True, margin_titles=False, facet_kws=None, ci=<deprecated>, **kwargs)

#Kategorik grafiklarni FacetGrid ichiga chizish uchun figurali interfeys.

Bu funksiya bir yoki bir nechta kategorik o‘zgaruvchi bilan raqamli o‘zgaruvchi o‘rtasidagi munosabatni turli vizual ko‘rinishlarda ko‘rsatadigan bir nechta o‘q darajasidagi funksiyalarga kirish imkonini beradi. kind parametri qaysi funksiyadan foydalanishni belgilaydi.

#Kategorik scatterplotlar:

`stripplot()` (`kind="strip"`, `standart`)

`swarmplot()` (`kind="swarm"`)

#Kategorik taqsimot grafiklari:

`boxplot()` (`kind="box"`)

`violinplot()` (`kind="violin"`)

`boxenplot()` (`kind="boxen"`)

#Kategorik baholash grafiklari:

`pointplot()` (`kind="point"`)

`barplot()` (`kind="bar"`)

`countplot()` (`kind="count"`)

Qo‘shimcha kalit argumentlar (keyword arguments) asosiy funksiyaga uzatiladi. Shu sababli, har bir tur uchun maxsus parametrlarni ko‘rish uchun ularning hujjatlariga murojaat qilish kerak.
"""