# -*- coding: utf-8 -*-
"""seaborn.catplot-kodlarlar

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NXIwGWSu53iZHbye4ggBJa4DNQRv3Vs1

Kerakli kutibxonalarni chaqirib olamiz:
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

"""Bizga kerakli data ni yuklab olamiz"""

df = sns.load_dataset("titanic")
df.head()

sns.catplot(data=df, x="age", y="class")
plt.show()

sns.catplot(data=df, x="age", y="class", kind="box")
plt.show()

sns.catplot(data=df, x="age", y="class", hue="sex", kind="boxen")
plt.show()

sns.catplot(
    data=df, x="age", y="class", hue="sex",
    kind="violin", bw_adjust=.5, cut=0, split=True,
)
plt.show()

sns.catplot(
    data=df, x="class", y="survived", col="sex",
    kind="bar", height=4, aspect=.6,
)
plt.show()

sns.catplot(data=df, x="age", y="class", kind="violin", color=".9", inner=None)
sns.swarmplot(data=df, x="age", y="class", size=3)
plt.show()

