# -*- coding: utf-8 -*-
"""seaborn.lineplot-malumotlar

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kXxnZ3q_vdqM1vV0ndj1GkYrA4I27GKU

#seaborn.lineplot
seaborn.lineplot(data=None, *, x=None, y=None, hue=None, size=None, style=None, units=None, weights=None, palette=None, hue_order=None, hue_norm=None, sizes=None, size_order=None, size_norm=None, dashes=True, markers=None, style_order=None, estimator='mean', errorbar=('ci', 95), n_boot=1000, seed=None, orient='x', sort=True, err_style='band', err_kws=None, legend='auto', ci='deprecated', ax=None, **kwargs)

#Chiziqli grafikni bir nechta semantik guruhlash imkoniyati bilan chizish.

x va y o‘zgaruvchilari orasidagi munosabatlarni `hue`, `size` va `style` parametrlaridan foydalanib, ma’lumotlarning turli bo‘laklari (subsetlari) uchun ko‘rsatish mumkin.

Bu parametrlar turli bo‘laklarni ajratib ko‘rsatish uchun qanday vizual semantikalar ishlatilishini boshqaradi.

Uchta semantik turdan bir vaqtda foydalanib, uch o‘lchovli munosabatlarni ham ko‘rsatish mumkin, lekin bunday grafikni talqin qilish qiyin bo‘lishi va har doim ham samarali bo‘lmasligi mumkin.

Bir xil o‘zgaruvchiga ortiqcha semantika (masalan, rang ham, uslub ham) berish esa grafikani yanada tushunarli qilishda foydali bo‘lishi mumkin.

👉 Qo‘shimcha ma’lumot uchun qo‘llanmaga qarang.

`Hue` (va kamroq darajada `size`) semantikasi ishlatilganda, uning standart talqini o‘zgaruvchining “sonli” yoki “kategorik” ekanligiga bog‘liq bo‘ladi.

Sonli o‘zgaruvchilar odatda ketma-ket ranglar xaritasi (sequential colormap) bilan ifodalanadi.

Afsonadagi (legend) yozuvlar esa muntazam “bo‘linishlar” bilan ko‘rsatiladi, hatto bu qiymatlar ma’lumotlarda bo‘lmasa ham.


Bu xatti-harakatni turli parametrlar orqali boshqarish mumkin

Standart holatda, grafik har bir x qiymati uchun bir nechta y qiymatlarini birlashtiradi va shu qiymatlarning markaziy moyilligi (masalan, o‘rtacha qiymat) bilan birga ishonchlilik oralig‘ini (confidence interval) ham ko‘rsatadi.

`scatterplot` – nuqtalar yordamida ma’lumotlarni tasvirlash.

`pointplot` – belgilar va chiziqlar yordamida nuqta baholari (point estimates) va ishonchlilik oralig‘i (CI) ni ko‘rsatish.
"""