# -*- coding: utf-8 -*-
"""seaborn_ecdfplot-kodlar

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dCXkEg0RavqHJUl8HORY1oU65uemYOvm

Kerakli kutubxonalarni chaqirib olamiz:
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

"""Bizga kerakli data ni yuklab olamiz"""

penguins = sns.load_dataset("penguins")
penguins.head()

sns.ecdfplot(data=penguins, x="flipper_length_mm")
plt.show()

sns.ecdfplot(data=penguins, y="flipper_length_mm")
plt.show()

"""bill_ soz'zi bilan boshlanadigan columnlarni filtrlab olamiz va shu bo'yicha grafik chizamiz:"""

sns.ecdfplot(data=penguins.filter(like="bill_", axis="columns"))
plt.show()

sns.ecdfplot(data=penguins, x="bill_length_mm", hue="species")
plt.show()

"""Standart taqsimot statistikasi ulushni (`proportion`) ko‘rsatish uchun normallashtiriladi, ammo siz o‘rniga mutlaq sanog‘ini (`count`) yoki foizlarni (`percent`) ko‘rsatishingiz mumkin."""

sns.ecdfplot(data=penguins, x="bill_length_mm", hue="species", stat="count")
plt.show()

