# -*- coding: utf-8 -*-
"""seaborn_ecdfplot-malumotlar

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dCXkEg0RavqHJUl8HORY1oU65uemYOvm

#seaborn.ecdfplot
`seaborn.ecdfplot`(data=None, *, x=None, y=None, hue=None, weights=None, stat='proportion', complementary=False, palette=None, hue_order=None, hue_norm=None, log_scale=None, legend=True, ax=None, **kwargs)

`ECDF` (Empirik Kumuliyativ Taqsimot Funktsiyasi) datasetdagi har bir noyob qiymatdan pastga tushadigan kuzatuvlarning ulushi yoki sonini ifodalaydi.

 Gistogramma yoki zichlik grafigiga nisbatan uning afzalligi shundaki, har bir kuzatuv to‘g‘ridan-to‘g‘ri vizuallashtiriladi, ya’ni bin (bo‘linma) yoki `smoothing` (silliqlash) parametrlarini sozlash zarur emas. Bundan tashqari, bir nechta taqsimotlarni bevosita taqqoslashga yordam beradi. Kamchiligi shundaki, grafik ko‘rinishi bilan taqsimotning asosiy xususiyatlari (masalan, markaziy tendensiya, dispersiya yoki bimodallik mavjudligi) o‘rtasidagi
 bog‘liqlik unchalik intuitiv bo‘lmasligi mumkin.

#Parametrlar:

data (`pandas.DataFrame`, `numpy.ndarray`, `mapping` yoki `sequence`)
Kirish ma’lumotlar tuzilmasi. Uzoq shakldagi (long-form) vektorlardan tashkil topgan to‘plam bo‘lishi mumkin, ular nomlangan o‘zgaruvchilarga biriktiriladi. Yoki keng shakldagi (wide-form) dataset bo‘lishi mumkin, bu holda u ichki tarzda qayta shakllantiriladi.

`x`, `y` (vektorlar yoki data ichidagi kalitlar)
Grafikning x va y o‘qlaridagi joylashuvni belgilovchi o‘zgaruvchilar.

`hue` (vektor yoki data ichidagi kalit)
Rang elementlarini belgilash uchun xaritalanadigan semantik o‘zgaruvchi.

`weights` (vektor yoki data ichidagi kalit)
Agar ko‘rsatilsa, mos keluvchi ma’lumot nuqtalarining kumulyativ taqsimotdagi hissasi shu qiymatlar bilan og‘irlanadi.

`stat` {{“proportion”, “percent”, “count”}}
Hisoblanadigan taqsimot statistikasi.

`complementary` (bool)
Agar True bo‘lsa, komplementar CDF (1 – CDF) ishlatiladi.

`palette` (string, list, dict, yoki matplotlib.colors.Colormap)
Ranglarni tanlash usuli. String qiymatlar color_palette() ga uzatiladi. List yoki dict kategorik xaritalashni bildiradi, colormap esa sonli xaritalashni bildiradi.

`hue_order` (stringlar vektori)
Hue semantikasidagi kategoriyalarni qay tartibda qayta ishlash va chizishni belgilaydi.

`hue_norm` (tuple yoki matplotlib.colors.Normalize)
Ikki qiymatli juftlik bo‘lib, normalizatsiya diapazonini (data birliklarida) belgilaydi. Yoki obyekt bo‘lib, data qiymatlarini [0, 1] intervaliga xaritalaydi. Sonli xaritalashni bildiradi.

`log_scale` (bool yoki number, yoki bool/number juftligi)
O‘qlarni log masshtabga o‘tkazish. Bitta qiymat — barcha sonli o‘qlar uchun log masshtab bazasini (standart 10) bildiradi. Ikki qiymat berilsa, har bir o‘q uchun alohida o‘rnatiladi. None yoki False bo‘lsa, seaborn mavjud Axes o‘q masshtabiga amal qiladi.

`legend` (bool)
Agar False bo‘lsa, semantik o‘zgaruvchilar uchun legenda chiqarilmaydi.

`ax` (matplotlib.axes.Axes)
Grafik chizish uchun oldindan yaratilgan o‘qlar. Agar berilmasa, matplotlib.pyplot.gca() ichki chaqiriladi.

`kwargs`
Boshqa kalit so‘z argumentlari matplotlib.axes.Axes.plot() funksiyasiga uzatiladi.
"""