# -*- coding: utf-8 -*-
"""seaborn.histplot-kodlar

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mc_F2OHeO6mg4CC5gnr4kGvkxrrYpbAT

Kerakli kutubxonalarni chaqirib olamiz:
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

"""Bizga kerakli datani yuklab olamiz:"""

penguins = sns.load_dataset("penguins")
penguins.head()

sns.histplot(data=penguins, x="flipper_length_mm")
plt.show()

sns.histplot(data=penguins, y="flipper_length_mm")
plt.show()

sns.histplot(data=penguins, x="flipper_length_mm", binwidth=3)
plt.show()

sns.histplot(data=penguins, x="flipper_length_mm", bins=30)
plt.show()

sns.histplot(data=penguins, x="flipper_length_mm", kde=True)
plt.show()

sns.histplot(data=penguins)
plt.show()

sns.histplot(data=penguins, x="flipper_length_mm", hue="species")
plt.show()

"""Bir nechta taqsimotlarni chizishning standart usuli ularni ‘qatlamlash’ (`layer`) hisoblanadi, ammo siz ularni ‘ustma-ust qo‘yish’ (`stack`) orqali ham tasvirlashingiz mumkin."""

sns.histplot(data=penguins, x="flipper_length_mm", hue="species", multiple="stack")
plt.show()

sns.histplot(penguins, x="flipper_length_mm", hue="species", element="step")
plt.show()

"""Siz ustunlardan (`bar`lardan) yanada uzoqlashib, har bir bin markazida joylashgan uchlari (`vertex`) bo‘yicha ko‘pburchak (polygon) chizishingiz mumkin. Bu taqsimot shaklini ko‘rishni osonlashtirishi mumkin, ammo ehtiyotkorlik bilan foydalaning: tomoshabinlar bu histogramma ekanini darhol anglamasliklari mumkin."""

sns.histplot(penguins, x="flipper_length_mm", hue="species", element="poly")
plt.show()

sns.histplot(
    penguins, x="bill_length_mm", hue="island", element="step",
    stat="density", common_norm=False,
)
plt.show()

planets = sns.load_dataset("planets")
sns.histplot(data=planets, x="distance")
plt.show()

sns.histplot(penguins, x="bill_depth_mm", y="body_mass_g")
plt.show()

sns.histplot(penguins, x="bill_depth_mm", y="body_mass_g", hue="species")
plt.show()

sns.histplot(
    penguins, x="bill_depth_mm", y="species", hue="species", legend=False
)
plt.show()

