# -*- coding: utf-8 -*-
"""seaborn.histplot-malumotlar

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mc_F2OHeO6mg4CC5gnr4kGvkxrrYpbAT

##`seaborn.histplot`
`seaborn.histplot`(data=None, *, x=None, y=None, hue=None, weights=None, stat='count', bins='auto', binwidth=None, binrange=None, discrete=None, cumulative=False, common_bins=True, common_norm=True, multiple='layer', element='bars', fill=True, shrink=1, kde=False, kde_kws=None, line_kws=None, thresh=0, pthresh=None, pmax=None, cbar=False, cbar_ax=None, cbar_kws=None, palette=None, hue_order=None, hue_norm=None, color=None, log_scale=None, legend=True, ax=None, **kwargs)

`Histogramma` — ma’lumotlarni taqsimotini ko‘rsatish

`Histogramma` — bu klassik vizualizatsiya vositasi bo‘lib, u bitta yoki bir nechta o‘zgaruvchilarning taqsimotini ko‘rsatadi. U qiymatlarni alohida “bin” (interval yoki quti) larda guruhlab, nechta kuzatuv shu oraliqqa tushganini sanaydi.

🔹 `histplot()` funksiyasi quyidagilarni qila oladi:

Har bir bin ichidagi statistikani chastota, zichlik yoki ehtimollik massasi sifatida normallashtirishi mumkin.

Shuningdek, `KDE` (Kernel Density Estimate) yordamida yumshoq egri chiziqni chizib beradi (`kdeplot()` ga o‘xshash).


Qo‘shimcha ma’lumotni foydalanuvchi qo‘llanmasida ko‘rish mumkin.


---

Parametrlar

`data` (`pandas.DataFrame`, `numpy.ndarray`, `mapping` yoki ketma-ketlik)
Kiritiladigan ma’lumotlar. U long-form (ustunlar nomiga tayangan vektorlar) yoki wide-form (keyinchalik ichida qayta shakllanadigan) bo‘lishi mumkin.

`x`, `y` (vektor yoki data ichidagi ustun nomlari)
`X` va `Y` o‘qlaridagi o‘zgaruvchilarni belgilaydi.

`hue` (vektor yoki data ichidagi ustun nomi)
Rang bo‘yicha ajratishni boshqaradigan semantik o‘zgaruvchi.

`weights` (vektor yoki data ichidagi ustun nomi)
Har bir nuqtaning umumiy hisobga qo‘shadigan og‘irligini belgilash uchun ishlatiladi.



---

Statistik parametrlar (stat)

`Bin` ichida hisoblanadigan natija turi:

`count`: har bir bin ichidagi kuzatuvlar soni

`frequency`: bin kengligiga bo‘lingan soni

`probability` yoki `proportion`: ustun balandliklari yig‘indisi = 1 bo‘ladi

`percent`: ustun balandliklari yig‘indisi = 100 bo‘ladi

`density`: histogramma ostidagi umumiy maydon = 1 bo‘ladi



---

Binning (interval ajratish)

`bins` (str, son, vektor, yoki juftlik)
`Bin` soni yoki chegaralarini belgilaydi (`numpy.histogram_bin_edges()` ga uzatiladi).

`binwidth` (son yoki juftlik)
Har bir bin kengligi.

`binrange` (ikki son yoki juftlik)
Binlar uchun minimal va maksimal qiymat.



---

Qo‘shimcha opsiyalar

`discrete` (bool) → Diskret ma’lumotlar uchun (`binwidth=1`).

`cumulative` (bool) → Kumulativ chastotani ko‘rsatadi.

`common_bins` (bool) → Bir nechta guruhlar uchun umumiy binlardan foydalanish.

`common_norm` (bool) → Normallashtirishni butun dataset bo‘yicha bajarish yoki alohida.



---

Ko‘p elementli histogramma

`multiple` {layer, dodge, stack, fill} → Bir nechta guruhlarni qanday joylashtirish.

element {bars, step, poly} → Histogrammaning ko‘rinishi.

`fill` (bool) → Barlar ostini rang bilan to‘ldirish.

`shrink` (son) → Har bir bar kengligini kamaytirish.



---

`KDE` (Kernel Density Estimate)

`kde` (bool) → KDE chizilishini ko‘rsatish.

`kde_kws` (dict) → KDE hisoblash parametrlarini sozlash.

`line_kws` (dict) → KDE chizig‘ining grafik ko‘rinishini sozlash.



---

Bivariate (ikkita o‘zgaruvchi uchun)

`thresh` (son yoki None) → Shu qiymatdan kichik binlar ko‘rinmaydi.

`pthresh` (0–1 oralig‘ida son) → Umumiy natijaga nisbatan shaffoflik chegarasi.

`pmax` (0–1 oralig‘ida son) → Rang intensivligini belgilash.

`cbar` (bool) → Rangli shkala (`colorbar`) qo‘shish.



---

Rang va legenda

`palette` (str, list, dict, colormap) → Ranglarni tanlash usuli.

`hue_order` (list) → Kategoriyalarni tartibini belgilash.

`hue_norm` (tuple yoki Normalize) → Ranglarni normallashtirish.

`color` (matplotlib color) → Bitta rang belgilash.

`legend` (bool) → Legenda ko‘rsatish/ko‘rsatmaslik.



---

O‘lchamlar va joylashuv

`log_scale` (bool, son yoki juftlik) → O‘qlarni logarifmik masshtabda ko‘rsatish.

`ax` (matplotlib.axes.Axes) → Oldindan mavjud o‘qni ishlatish.
"""