# -*- coding: utf-8 -*-
"""seaborn_kdeplot-kodlar

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N6U9aezQ-7QJiSP1ZjSY24IAq9kYG6q-

Kerakli kutubxonalarni yuklab olamiz:
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

"""data yuklab olamiz:"""

tips = sns.load_dataset("tips")
tips.head()

sns.kdeplot(data=tips, x="total_bill")
plt.show()

sns.kdeplot(data=tips, y="total_bill")
plt.show()

"""Boshqa data bo'yicha grafikni davom ettiramiz:"""

iris = sns.load_dataset("iris")
iris.head()

sns.kdeplot(data=iris)
plt.show()

sns.kdeplot(data=tips, x="total_bill", bw_adjust=.2)
plt.show()

sns.kdeplot(data=tips, x="total_bill", hue="time")
plt.show()

sns.kdeplot(data=tips, x="total_bill", hue="time", multiple="stack")
plt.show()

sns.kdeplot(data=tips, x="total_bill", hue="time", multiple="fill")
plt.show()

diamonds = sns.load_dataset("diamonds")
sns.kdeplot(data=diamonds, x="price", log_scale=True)
plt.show()

sns.kdeplot(data=tips, x="total_bill", hue="size")
plt.show()

sns.kdeplot(
   data=tips, x="total_bill", hue="size",
   fill=True, common_norm=False, palette="crest",
   alpha=.5, linewidth=0,
)
plt.show()

geyser = sns.load_dataset("geyser")
sns.kdeplot(data=geyser, x="waiting", y="duration")
plt.show()

sns.kdeplot(data=geyser, x="waiting", y="duration", hue="kind")
plt.show()

sns.kdeplot(
    data=geyser, x="waiting", y="duration", hue="kind", fill=True,
)
plt.show()

sns.kdeplot(
    data=geyser, x="waiting", y="duration",
    fill=True, thresh=0, levels=100, cmap="mako",
)
plt.show()

