# -*- coding: utf-8 -*-
"""seaborn_kdeplot-malumotlar

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N6U9aezQ-7QJiSP1ZjSY24IAq9kYG6q-

##seaborn.kdeplot
`seaborn.kdeplot`(data=None, *, x=None, y=None, hue=None, weights=None, palette=None, hue_order=None, hue_norm=None, color=None, fill=None, multiple='layer', common_norm=True, common_grid=False, cumulative=False, bw_method='scott', bw_adjust=1, warn_singular=True, log_scale=None, levels=10, thresh=0.05, gridsize=200, cut=3, clip=None, legend=True, cbar=False, cbar_ax=None, cbar_kws=None, ax=None, **kwargs)

Yadro zichligini baholash (Kernel Density Estimation, `KDE`) yordamida bir o‘lchovli yoki ikki o‘lchovli taqsimotlarni chizing.

`KDE` grafigi — ma’lumotlar to‘plamidagi kuzatuvlar taqsimotini vizualizatsiya qilish usuli bo‘lib, u gistogrammaga o‘xshashdir. KDE ma’lumotlarni bir yoki bir nechta o‘lchamda uzluksiz ehtimollik zichligi egri chizig‘i orqali ifodalaydi.

Gistogrammaga nisbatan, KDE grafikni kamroq chalkash va tushunarliroq
ko‘rsatishi mumkin, ayniqsa bir nechta taqsimotlar chizilganda. Lekin, agar asosiy taqsimot chegaralangan yoki silliq bo‘lmasa, u noto‘g‘ri ko‘rinishlarga olib kelishi mumkin. Gistogrammadagi kabi, ifodaning sifati ham yaxshi silliqlash parametrlarini tanlashga bog‘liq.

#Izohlar:

Silliqlash yadrosining (`kernel`) kengligi (`bandwidth`) yoki standart og‘ishi muhim parametr hisoblanadi.

`Bandwidth` noto‘g‘ri tanlansa, ma’lumotlarning buzilgan tasviri yuzaga kelishi mumkin. Xuddi gistogrammadagi bin kengligini tanlash kabi, ortiqcha silliqlangan egri taqsimotning haqiqiy xususiyatlarini yo‘qotishi mumkin, juda oz silliqlash esa tasodifiy o‘zgarishlardan noto‘g‘ri xususiyatlarni yaratib
qo‘yishi mumkin.

`Standart bandwidth` tanlov qoidasi haqiqiy taqsimot silliq, bitta cho‘qqili (`unimodal`) va taxminan qo‘ng‘iroqsimon shaklda bo‘lganda eng yaxshi ishlaydi. Shuning uchun `bw_adjust` parametridan foydalanib silliqlash darajasini oshirish yoki kamaytirish orqali standart xatti-harakatni tekshirish foydali
bo‘ladi.

Silliqlash algoritmi `Gauss` yadrosidan foydalanadiganligi sababli, baholangan zichlik egri chizig‘i ayrim hollarda ma’lumotlar uchun mantiqsiz qiymatlarga ham cho‘zilishi mumkin.

Masalan, tabiatan musbat qiymatlardan iborat ma’lumotlarda, egri manfiy qiymatlar ustida ham chizilishi mumkin. Bunday hollarda `cut` va `clip` parametrlari egri chizig‘ining qamrovini cheklash uchun ishlatiladi, lekin tabiiy chegaraga yaqin ko‘plab kuzatuvlarga ega datasetlar uchun boshqa vizualizatsiya usulidan foydalanish yaxshiroq bo‘lishi mumkin.

Shunga o‘xshash mulohazalar `dataset` tabiatan `diskret` yoki `‘spiky’` (bir xil qiymat ko‘p marotaba takrorlangan) bo‘lganda ham qo‘llanadi. `Kernel` zichligini baholash (`KDE`) har doim silliq egri chizig‘ini hosil qiladi, bu esa bunday holatlarda noto‘g‘ri tasavvur uyg‘otishi mumkin.

Zichlik o‘qi (`density axis`)dagi birliklar ko‘pincha chalkashlikka sabab
bo‘ladi. Kernel zichligini baholash ehtimollik taqsimotini hosil qilsa-da, egri chiziqning balandligi ma’lum bir nuqtadagi ehtimollikni emas, balki zichlikni ko‘rsatadi.

Ehtimollikni faqat ma’lum oraliq bo‘yicha zichlikni integrallash orqali olish mumkin. Egri chiziq umumiy integral 1 ga teng bo‘ladigan qilib normallashtiriladi, ya’ni zichlik o‘qi masshtabi ma’lumot qiymatlariga bog‘liq bo‘ladi.
"""